CREATE DATABASE DB_ESCOLA;

USE DB_ESCOLA;

CREATE TABLE TB_ESTUDANTES(
RA BIGINT AUTO_INCREMENT,
NOME VARCHAR (1000),
IDADE INT,
ANO INT,
SALA CHAR (255),
NOTA_FINAL DECIMAL,
PRIMARY KEY (RA)
);

INSERT INTO TB_ESTUDANTES (NOME,IDADE,ANO,SALA,NOTA_FINAL) VALUES ("NAYARA",6,1,"A",8.0);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,ANO,SALA,NOTA_FINAL) VALUES ("ADAM",7,2,"B",7.5);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,ANO,SALA,NOTA_FINAL) VALUES ("BARBARA",8,3,"C",10.0);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,ANO,SALA,NOTA_FINAL) VALUES ("BIANCA",9,4,"A",5.3);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,ANO,SALA,NOTA_FINAL) VALUES ("YASMIN",10,5,"B",6.2);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,ANO,SALA,NOTA_FINAL) VALUES ("JOÃO",11,6,"C",9.7);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,ANO,SALA,NOTA_FINAL) VALUES ("HENRIQUE",12,7,"A",4.8);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,ANO,SALA,NOTA_FINAL) VALUES ("ROSANGELA",13,8,"B",7.5);

SELECT * FROM TB_ESTUDANTES;

SELECT * FROM TB_ESTUDANTES WHERE NOTA_FINAL > 7.0;
SELECT * FROM TB_ESTUDANTES WHERE NOTA_FINAL < 7.0;

SET SQL_SAVE_UPDATES = 0;

UPDATE TB_ESTUDANTES SET SALA = "C" WHERE RA = 8;