CREATE DATABASE DB_GENERATION_GAME_ONLINE;
USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES(
    ID BIGINT(5) AUTO_INCREMENT,
    CLASSE VARCHAR(255) NOT NULL,
    FORCA BIGINT (5),
    INTELIGENCIA BIGINT (5),
    PRIMARY KEY(ID)
);

CREATE TABLE TB_PERSONAGENS(
    ID BIGINT(5) AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    PODER VARCHAR(255) NOT NULL,
    ATAQUE BIGINT (5),
    DEFESA BIGINT (5),
    CLASSE_ID BIGINT,
    PRIMARY KEY(ID),
	FOREIGN KEY(CLASSE_ID) REFERENCES TB_CLASSES(ID)
);

INSERT INTO TB_CLASSES(CLASSE,FORCA,INTELIGENCIA)
VALUES ("ARQUEIRO",2000,5000);
INSERT INTO TB_CLASSES(CLASSE,FORCA,INTELIGENCIA)
VALUES ("CURANDEIRO",1000,4000);
INSERT INTO TB_CLASSES(CLASSE,FORCA,INTELIGENCIA)
VALUES ("FEITICEIRO",2000,7000);
INSERT INTO TB_CLASSES(CLASSE,FORCA,INTELIGENCIA)
VALUES ("ANSIÃO",500,10000);
INSERT INTO TB_CLASSES(CLASSE,FORCA,INTELIGENCIA)
VALUES ("GUERREIRO",4000,2000);

SELECT * FROM TB_CLASSES;

DELETE FROM TB_CLASSES WHERE ID =1;

INSERT INTO TB_PERSONAGENS(NOME,PODER,ATAQUE,DEFESA,CLASSE_ID)
VALUES ("OXOSSI","OFÁ",3000,2000,2);
INSERT INTO TB_PERSONAGENS(NOME,PODER,ATAQUE,DEFESA,CLASSE_ID)
VALUES ("OGUM","FERRO",6000,4000,6);
INSERT INTO TB_PERSONAGENS(NOME,PODER,ATAQUE,DEFESA,CLASSE_ID)
VALUES ("IANSÃ","VENTO",5000,3000,6);
INSERT INTO TB_PERSONAGENS(NOME,PODER,ATAQUE,DEFESA,CLASSE_ID)
VALUES ("EXU","CABAÇA",7000,3000,4);
INSERT INTO TB_PERSONAGENS(NOME,PODER,ATAQUE,DEFESA,CLASSE_ID)
VALUES ("YEMANJÁ","ÁGUA",1000,5000,3);
INSERT INTO TB_PERSONAGENS(NOME,PODER,ATAQUE,DEFESA,CLASSE_ID)
VALUES ("OXUM","OURO",3000,7000,4);
INSERT INTO TB_PERSONAGENS(NOME,PODER,ATAQUE,DEFESA,CLASSE_ID)
VALUES ("NANÃ","IBIRI",1000,2000,5);
INSERT INTO TB_PERSONAGENS(NOME,PODER,ATAQUE,DEFESA,CLASSE_ID)
VALUES ("XANGÔ","MACHADO",4000,2000,6);

SELECT * FROM TB_PERSONAGENS;

SELECT * FROM TB_PERSONAGENS WHERE ATAQUE > 2000;

SELECT * FROM TB_PERSONAGENS WHERE DEFESA >= 1000 AND DEFESA <=2000;

SELECT * FROM TB_PERSONAGENS WHERE NOME LIKE "%C%";

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON
TB_PERSONAGENS.CLASSE_ID = TB_CLASSES.ID;

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON
TB_CLASSES.CLASSE = "ANSIÃO" AND TB_PERSONAGENS.CLASSE_ID = 5;

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON
TB_CLASSES.CLASSE = "GUERREIRO" AND TB_PERSONAGENS.CLASSE_ID = 6;