CREATE DATABASE DB_PIZZARIA_LEGAL;

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT (5) AUTO_INCREMENT,
TAMANHO VARCHAR(255) NOT NULL,  -- INDIVIDUAL, PEQUENA, MÉDIA, GRANDE, FAMÍLIA
PRECO FLOAT (6,2) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZAS (
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR (255) NOT NULL,
SABOR VARCHAR(255) NOT NULL, -- DOCE OU SALGADO
RESTRICAO VARCHAR (255) NOT NULL, -- TRADICIONAL, VEGETARIANO, VEGANO, SEM GLUTEN
TAMANHO_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (TAMANHO_ID) REFERENCES TB_CATEGORIAS(ID)
);


INSERT INTO TB_CATEGORIAS(TAMANHO,PRECO)
VALUES ("INDIVIDUAL",30.00);
INSERT INTO TB_CATEGORIAS(TAMANHO,PRECO)
VALUES ("PEQUENA",50.00);
INSERT INTO TB_CATEGORIAS(TAMANHO,PRECO)
VALUES ("MÉDIA",70.00);
INSERT INTO TB_CATEGORIAS(TAMANHO,PRECO)
VALUES ("GRANDE",90.00);
INSERT INTO TB_CATEGORIAS(TAMANHO,PRECO)
VALUES ("FAMÍLIA",110.00);

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PIZZAS (NOME,SABOR,RESTRICAO,TAMANHO_ID)
VALUES ("FRANGO CREMOSO","SALGADA","TRADICIONAL",3);
INSERT INTO TB_PIZZAS (NOME,SABOR,RESTRICAO,TAMANHO_ID)
VALUES ("FRANGO CREMOSO","SALGADA","TRADICIONAL",4);
INSERT INTO TB_PIZZAS (NOME,SABOR,RESTRICAO,TAMANHO_ID)
VALUES ("FRANGO CREMOSO","SALGADA","TRADICIONAL",5);
INSERT INTO TB_PIZZAS (NOME,SABOR,RESTRICAO,TAMANHO_ID)
VALUES ("TOFU CROCANTE","SALGADA","VEGANA",3);
INSERT INTO TB_PIZZAS (NOME,SABOR,RESTRICAO,TAMANHO_ID)
VALUES ("TOFU CROCANTE","SALGADA","VEGANA",4);
INSERT INTO TB_PIZZAS (NOME,SABOR,RESTRICAO,TAMANHO_ID)
VALUES ("TOFU CROCANTE","SALGADA","VEGANA",5);
INSERT INTO TB_PIZZAS (NOME,SABOR,RESTRICAO,TAMANHO_ID)
VALUES ("MORANGO COM CHOCOLATE","DOCE","VEGETARIANA",1);
INSERT INTO TB_PIZZAS (NOME,SABOR,RESTRICAO,TAMANHO_ID)
VALUES ("MORANGO COM CHOCOLATE","DOCE","VEGETARIANA",2);

SELECT * FROM TB_PIZZAS;

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS WHERE PRECO > 45;

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS WHERE PRECO >= 50 AND PRECO <= 100;

SELECT * FROM TB_PIZZAS WHERE NOME LIKE "%M%";

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON
TB_PIZZAS.TAMANHO_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON
TB_PIZZAS.TAMANHO_ID = TB_CATEGORIAS.ID WHERE TAMANHO_ID = 4;