CREATE DATABASE DB_FARMACIA_BEM_ESTAR;

USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
CATEGORIA VARCHAR(255) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTOS (
COD_BARRAS BIGINT AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
PRECO FLOAT(6,2) NOT NULL,
CATEGORIA_ID BIGINT,
PRIMARY KEY (COD_BARRAS),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS (CATEGORIA)
VALUES ("HOMEM");
INSERT INTO TB_CATEGORIAS (CATEGORIA)
VALUES ("MULHER");
INSERT INTO TB_CATEGORIAS (CATEGORIA)
VALUES ("INFANTIL");
INSERT INTO TB_CATEGORIAS (CATEGORIA)
VALUES ("REMÉDIOS");
INSERT INTO TB_CATEGORIAS (CATEGORIA)
VALUES ("ALIMENTOS");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("KIT BARBA", 89.90, 1);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("COLETOR MENSTRUAL", 49.90, 2);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("LENÇO UMEDECIDO 48", 14.90, 3);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("NEOSALDINA 4 COMPRIMIDOS", 4.57, 4);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("TRIDENT", 2.00, 5);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("BARRA DE CEREAL", 2.50, 5);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("FRALDA PAMPERS SUPERSEC P 34", 49.90, 3);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("ANTICONCEPCIONAL", 39.9, 2);

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50;

SELECT * FROM TB_PRODUTOS WHERE PRECO >= 5 AND PRECO <= 60;

SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%";

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON
TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON
TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIAS.ID WHERE ID = 2;