CREATE DATABASE DB_CURSO_DA_MINHA_VIDA;

USE DB_CURSO_DA_MINHA_VIDA;

CREATE TABLE TB_CATEGORIAS (
ID BIGINT AUTO_INCREMENT,
ESCOLA VARCHAR (255) NOT NULL,
QTDD_CURSOS BIGINT,
PRIMARY KEY (ID)
);

CREATE TABLE TB_CURSOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
VALOR FLOAT (6,2),
HORAS_CURSO INT,
ESCOLA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (ESCOLA_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS (ESCOLA,QTDD_CURSOS)
VALUES ("PROGRAMACAO",304);
INSERT INTO TB_CATEGORIAS (ESCOLA,QTDD_CURSOS)
VALUES ("FONT_END",103);
INSERT INTO TB_CATEGORIAS (ESCOLA,QTDD_CURSOS)
VALUES ("DATA_SCIENCE",204);
INSERT INTO TB_CATEGORIAS (ESCOLA,QTDD_CURSOS)
VALUES ("MOBILE", 78);
INSERT INTO TB_CATEGORIAS (ESCOLA,QTDD_CURSOS)
VALUES ("GESTÃO",279);

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_CURSOS (NOME,VALOR,HORAS_CURSO,ESCOLA_ID)
VALUES ("LOGICA",300,67,1);
INSERT INTO TB_CURSOS (NOME,VALOR,HORAS_CURSO,ESCOLA_ID)
VALUES ("JAVA",500,112,1);
INSERT INTO TB_CURSOS (NOME,VALOR,HORAS_CURSO,ESCOLA_ID)
VALUES ("HTML",400,89,2);
INSERT INTO TB_CURSOS (NOME,VALOR,HORAS_CURSO,ESCOLA_ID)
VALUES ("CSS",400,89,2);
INSERT INTO TB_CURSOS (NOME,VALOR,HORAS_CURSO,ESCOLA_ID)
VALUES ("SQL",700,156,3);
INSERT INTO TB_CURSOS (NOME,VALOR,HORAS_CURSO,ESCOLA_ID)
VALUES ("FLUTTER",450,100,4);
INSERT INTO TB_CURSOS (NOME,VALOR,HORAS_CURSO,ESCOLA_ID)
VALUES ("AGILE",350,78,5);
INSERT INTO TB_CURSOS (NOME,VALOR,HORAS_CURSO,ESCOLA_ID)
VALUES ("COMUNICACAO",200,45,5);

SELECT * FROM TB_CURSOS;

SELECT * FROM TB_CURSOS WHERE VALOR > 500;
SELECT * FROM TB_CURSOS WHERE VALOR >= 600 AND VALOR <= 1000;
SELECT * FROM TB_CURSOS WHERE NOME LIKE "%J%";

SELECT * FROM TB_CURSOS INNER JOIN TB_CATEGORIAS ON
TB_CURSOS.ESCOLA_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_CURSOS INNER JOIN TB_CATEGORIAS ON
TB_CURSOS.ESCOLA_ID = TB_CATEGORIAS.ID WHERE ESCOLA_ID = 1;